name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'production'


