name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Run Tests
        if: ${{ contains(github.event.head_commit.message,'test commit') }}
        run: mvn test

      - name: Upload JAR to Github
        if: ${{success()}}
        uses: actions/upload-artifact@v3
        with:
          name: myapp-jar
          path: target/*.jar




