name: Deploy


on:
  workflow_call:
    inputs:
      build_status:
        description: 'Build status'
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Run Tests
        if: ${{ contains(github.event.head_commit.message,'test commit') }}
        run: mvn test

      - name: Check results
        run: |
          echo "event = ${{github.event_name}} "
          echo "Repository = ${{github.repository}}"
          echo "JOB ID = ${{github.job}}"
          echo "Run ID : ${{github.run_id}}"
          echo "user = ${{github.actor}}"


      - name: Upload JAR to Github
        if: ${{success()}}
        uses: actions/upload-artifact@v3
        with:
          name: myapp-jar
          path: target/*.jar

    outputs:
      build-status:
        description: 'Build status'
        value: 'Success'