name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: string
    outputs:
      build-status:
        description: 'Status of the build'
        value: ${{ steps.set_output.outputs.build-status }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Run Tests
        if: ${{ contains(github.event.head_commit.message, 'test commit') }}
        run: mvn test

      - name: Check results
        run: |
          echo "event = ${{ github.event_name }}"
          echo "Repository = ${{ github.repository }}"
          echo "JOB ID = ${{ github.job }}"
          echo "Run ID : ${{ github.run_id }}"
          echo "user = ${{ github.actor }}"

      - name: Set output
        id: set_output
        run: echo "::set-output name=build-status::Success"

    outputs:
      build-status:
        description: 'Build status'
        value: ${{ steps.set_output.outputs.build-status }}
